<?xml version="1.0"?>
<!DOCTYPE Config [
  <!ELEMENT Config (Scheduler,Graph,DataAquisition,Algorithm*)>
  <!ELEMENT Scheduler (class,property*)>
  <!ELEMENT Graph (class,property*)>
  <!ELEMENT DataAquisition (class,property*)>
  <!ELEMENT Algorithm (class,property*)>
  <!ELEMENT class (#PCDATA)>
  <!ELEMENT property (name,value)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT value (#PCDATA)>
]>

<Config>
  <Scheduler>
    <class>basic</class>
  </Scheduler>
  <Graph>
    <class>MemGraph</class>
    <property>
      <name>GraphOutput</name>
      <value>/research/FastClique.xml</value>
    </property>
    <property>
      <name>Compression</name>
      <value>true</value>
    </property>
  </Graph>
  <DataAquisition>
    <class>File Reader 2 Pass</class>
    <property>
      <name>foafDirectory</name>
      <value>/research/data/backup-21-06-07</value>
    </property>
    <property>
      <name>anonymzing</name>
      <value>true</value>
    </property>
  </DataAquisition>
  <Algorithm>
    <class>EnumerateMaximalCliques</class>
  </Algorithm>
</Config>