<?xml version="1.0"?>
<!DOCTYPE Config [
  <!ELEMENT Config (Scheduler,Graph,DataAquisition,Algorithm*)>
  <!ELEMENT Scheduler (class,property*)>
  <!ELEMENT Graph (class,property*)>
  <!ELEMENT DataAquisition (class,property*)>
  <!ELEMENT Algorithm (class,property*)>
  <!ELEMENT class (#PCDATA)>
  <!ELEMENT property (name,value)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT value (#PCDATA)>
]>

<Config>
  <Scheduler>
    <class>basic</class>
  </Scheduler>
  <Graph>
    <class>MemGraph</class>
    <property>
      <name>GraphOutput</name>
      <value>/Users/mcennis/result.xml</value>
    </property>
  </Graph>
  <DataAquisition>
    <class>File Reader 2 Pass</class>
    <property>
      <name>foafDirectory</name>
      <value>/Users/mcennis/data/LiveJournalMini</value>
    </property>
    <property>
      <name>anonymizing</name>
      <value>true</value>
    </property>
  </DataAquisition>
  <Algorithm>
    <class>AddBasicInterestLink</class>
    <property>
      <name>adjustorPropertyType</name>
      <value></value>
    </property>
  </Algorithm>
  <Algorithm>
    <class>AddMusicReferences</class>
    <property>
      <name>decider</name>
      <value>basic</value>
    </property>
    <property>
      <name>artistListLocation</name>
      <value>/Users/mcennis/artist.txt</value>
    </property>
  </Algorithm>
  <Algorithm>
    <class>AddMusicLinks</class>
    <property>
      <name>adjustorPropertyType</name>
      <value></value>
    </property>
  </Algorithm>
  <Algorithm>
    <class>AddMusicRecommendations</class>
    <property>
      <name>adjustorPropertyType</name>
      <value></value>
    </property>
    <property>
      <name>evaluation</name>
      <value>true</value>
    </property>
  </Algorithm>
</Config>