<?xml version="1.0"?>
<!DOCTYPE Config [
  <!ELEMENT Config (Scheduler,Graph,DataAquisition,Algorithm*)>
  <!ELEMENT Scheduler (class,property*)>
  <!ELEMENT Graph (class,property*)>
  <!ELEMENT DataAquisition (class,property*)>
  <!ELEMENT Algorithm (class,pattern,property*)>
  <!ELEMENT class (#PCDATA)>
  <!ELEMENT pattern (#PCDATA)>
  <!ELEMENT property (name,value)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT value (#PCDATA)>
]>

<Config>
  <Scheduler>
    <class>basic</class>
  </Scheduler>
  <Graph>
    <class>MemGraph</class>
    <property>
      <name>GraphID</name>
      <value>Root</value>
    </property>
  </Graph>
  <DataAquisition>
    <class>Load Bibliography And Class</class>
    <property>
      <name>fileLocation</name>
      <value>/home/dm75/3_clusters.xml</value>
    </property>
    <property>
      <name>classLabelFile</name>
      <value>/home/dm75/idLabel.xml</value>
    </property>
  </DataAquisition>
  <Algorithm>
    <pattern>.*</pattern>
    <class>Identify Bridges</class>
    <property>
      <name>IncomingOutgoing</name>
      <value>IncomingOutgoing</value>
    </property>
    <property>
      <name>threshold</name>
      <value>0.1</value>
    </property>
    <property>
      <name>globalThreshold</name>
      <value>0.5</value>
    </property>
  </Algorithm>
  <Algorithm>
    <class>Output Bridges By Cluster</class>
    <pattern>.*</pattern>
    <property>
      <name>outputFile</name>
      <value>/home/dm75/public/bridgeByIncomingOutgoingLink.xml</value>
    </property>
  </Algorithm>
</Config>
