<?xml version="1.0"?><!DOCTYPE Config [  <!ELEMENT Config (Scheduler,Graph,DataAquisition,Algorithm*)>  <!ELEMENT Scheduler (class,property*)>  <!ELEMENT Graph (class,property*)>  <!ELEMENT DataAquisition (class,property*)>  <!ELEMENT Algorithm (class,pattern,property*)>  <!ELEMENT class (#PCDATA)>  <!ELEMENT pattern (#PCDATA)>  <!ELEMENT property (name,value)>  <!ELEMENT name (#PCDATA)>  <!ELEMENT value (#PCDATA)>]><Config>  <Scheduler>    <class>basic</class>  </Scheduler>  <Graph>    <class>MemGraph</class>    <property>      <name>GraphID</name>      <value>Root</value>    </property>  </Graph>  <DataAquisition>    <class>Load Bibliography And Class</class>    <property>      <name>fileLocation</name>      <value>c:\\Users\\mcennis\\Documents\\3_clusters.xml</value>    </property>    <property>      <name>classLabelFile</name>      <value>c:\\Users\\mcennis\\Documents\\idLabel.xml</value>    </property>  </DataAquisition>  <Algorithm>      <class>Basic Display Graph</class>      <pattern>.*</pattern>  </Algorithm></Config>