<?xml version="1.0"?>
<!DOCTYPE Config [
  <!ELEMENT Config (Scheduler,Graph,DataAquisition,Algorithm*)>
  <!ELEMENT Scheduler (class,property*)>
  <!ELEMENT Graph (class,property*)>
  <!ELEMENT DataAquisition (class,property*)>
  <!ELEMENT Algorithm (class,pattern,property*)>
  <!ELEMENT class (#PCDATA)>
  <!ELEMENT pattern (#PCDATA)>
  <!ELEMENT property (name,value)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT value (#PCDATA)>
]>

<Config>
  <Scheduler>
    <class>basic</class>
  </Scheduler>
  <Graph>
    <class>MemGraph</class>
    <property>
      <name>GraphID</name>
      <value>Root</value>
    </property>
  </Graph>
  <DataAquisition>
    <class>Get Artist Tags</class>
  </DataAquisition>
</Config>
